#!/usr/bin/env node
'use strict';

const fs = require('fs');
const path = require('path');

const outputPath = path.join(__dirname, '..', 'src', 'environments', 'environment.production.ts');
const localFallbackUrl = 'http://localhost:8000';
const isAutomatedBuild = process.env.CI === 'true' || Boolean(process.env.VERCEL);

let apiBaseUrl = process.env.API_BASE_URL;

if (!apiBaseUrl) {
  if (isAutomatedBuild) {
    console.error(
      '[generate-env] API_BASE_URL is not set. This is a CI or Vercel build, where it ' +
        'must be provided, check the API_BASE_URL secret/project env var is configured.',
    );
    process.exit(1);
  }

  console.warn(
    `[generate-env] API_BASE_URL is not set, falling back to ${localFallbackUrl} for this ` +
      'local build. This build will not reach a real backend, set API_BASE_URL if you need that.',
  );
  apiBaseUrl = localFallbackUrl;
}

const contents = [
  '// GENERATED by scripts/generate-env.js, do not edit by hand.',
  "// Regenerated on every `npm run build:prod` from the API_BASE_URL env var. See",
  "// generate-env.js for what happens when that env var isn't set.",
  'export const environment = {',
  '  production: true,',
  `  apiBaseUrl: '${apiBaseUrl}',`,
  '};',
  '',
].join('\n');

fs.writeFileSync(outputPath, contents);
console.log(`[generate-env] apiBaseUrl set to: ${apiBaseUrl}`);